<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxi9xxo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxi9xxo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVxi9xxo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVxi9xxo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVxi9xxo\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vxi9xxo',
    'container.build_id' => '91421e44',
    'container.build_time' => 1522956203,
));
